apiVersion: openslo/v1alpha
kind: SLO
metadata:
  displayName: SLO for all node component temps
  name: node-all-temps-slo
spec:
  budgetingMethod: Occurrences
  indicator:
    thresholdMetric:
      source: test/node_temps.csv
      queryType: pandas/csv
      # This evaluates to multiple metrics that differ by `sensor` column
      query: __name__ == "node_temp_celsius" and node=="klapek"
      metadata:
        multiSystem: true # Expect to get data for an arbitrary number of systems
        multiSystemColumns: [sensor] # Which data columns to use to differentiate between systems
  objectives:
  - op: lt
    value: 68 # °C
    target: 0.95
  timeWindow:
  - count: 28
    unit: Day
    isRolling: true
