apiVersion: openslo/v1alpha
kind: SLO
metadata:
  displayName: SLO for CPU temperature
  name: node-cpu-temp-slo
spec:
  budgetingMethod: Occurrences
  indicator:
    thresholdMetric:
      source: test/node_temps.csv
      queryType: pandas/csv
      # slo-evaluator uses Pandas lib internally, therefore the query is a Pandas dataframe query
      query: __name__ == "node_temp_celsius" and node=="klapek" and sensor=="cpu"
  objectives:
  - op: lt
    value: 90 # °C
    target: 0.95
  timeWindow:
  - count: 28
    unit: Day
    isRolling: true
